

export const trailData = [
    {id:"1",
    code:"CV0001",
    active:"",
    transaction: "venta",
    type: "casa",
    title: "Casa en barrio Poeta lugones",
    currency: "",
    price: "",
    creditAb: "",
    description: "",
    address: "",
    neighborhood: "",
    city: "",
    rooms: "",
    bedrooms: "",
    bathrooms: "",
    garages: "",
    totalArea: "",
    usableArea: "",
    pool: "",
    grill: "",
    gasSupply: "",
    images: [
        {url: "https://res.cloudinary.com/dqzgjxj6k/image/upload/"},
        {url: "https://res.cloudinary.com/dqzgjxj6k/image/upload/"},
        {url: "https://res.cloudinary.com/dqzgjxj6k/image/upload/"},
        {url: "https://res.cloudinary.com/dqzgjxj6k/image/upload/"},
        ],
    video:"",
    },
    {id:"2",
    code:"CV0002",
    active:"",
    transaction: "venta",
    type: "casa",
    title: "Casa en barrio Poeta lugones",
    currency: "",
    price: "",
    creditAb: "",
    description: "",
    address: "",
    neighborhood: "",
    city: "",
    rooms: "",
    bedrooms: "",
    bathrooms: "",
    garages: "",
    totalArea: "",
    usableArea: "",
    pool: "",
    grill: "",
    gasSupply: "",
    images: [
        {url: "https://res.cloudinary.com/dqzgjxj6k/image/upload/"},
        {url: "https://res.cloudinary.com/dqzgjxj6k/image/upload/"},
        {url: "https://res.cloudinary.com/dqzgjxj6k/image/upload/"},
        {url: "https://res.cloudinary.com/dqzgjxj6k/image/upload/"},
        ],
    video:"",
    },
]