import photo1 from '../assets/imgproducts/house1/one.jpeg'
import photo2 from '../assets/imgproducts/house1/two.jpeg'
import photo3 from '../assets/imgproducts/house1/three.jpeg'
import photo4 from '../assets/imgproducts/house1/four.jpeg'
import photo5 from '../assets/imgproducts/house1/five.jpeg'
import photo6 from '../assets/imgproducts/house1/six.jpeg'
import photo7 from '../assets/imgproducts/house1/seven.jpeg'
import photo8 from '../assets/imgproducts/house1/eigth.jpeg'
import photo9 from '../assets/imgproducts/house1/nine.jpeg'
import photo10 from '../assets/imgproducts/house1/ten.jpeg'
import photo11 from '../assets/imgproducts/house1/eleven.jpeg'
import photo12 from '../assets/imgproducts/house1/twelve.jpeg'
import photo13 from '../assets/imgproducts/house1/thirteen.jpeg'
import photo14 from '../assets/imgproducts/house1/fourteen.jpeg'
import photo15 from '../assets/imgproducts/house1/fifteen.jpeg'

export const trailData = [
    {id:"1",
    code:"CV0001",
    active: true,
    transaction: "venta",
    type: "casa",
    title: "Casa de tres dormitorios",
    price: 88000,
    dollar: true,
    creditAb: false,
    description: "Casa en Quintas de Arguello, 3 dormitorio, 2 baños, quincho cerrado, asador y patio amplio. Todos los servicios.",
    address: "Sergio Camargo 7966, X5021 Córdoba",
    neighborhood: "Quintas de Arguello",
    city: "Cordoba",
    rooms: 9,
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    totalArea: 70,
    usableArea: 50,
    pool: true,
    grill: true,
    gasSupply: "red",
    images: [
        {url: photo1},
        {url: photo2},
        {url: photo3},
        {url: photo4},
        {url: photo5},
        {url: photo6},
        {url: photo7},
        {url: photo8},
        {url: photo9},
        {url: photo10},
        {url: photo11},
        {url: photo12},
        {url: photo13},
        {url: photo14},
        {url: photo15},
    ],
    video:"",
    },
    {id:"2",
    code:"CV0002",
    active: true,
    transaction: "venta",
    type: "casa",
    title: "Casa de cuatro dormitorios",
    price: 110000,
    dollar: true,
    creditAb: true,
    description: "Casa en Villa Cabrera a seis cuadras del Shopping. Cuatro dormitorios, tres baños, garage cerrado, pileta climatizada, aire acondicionado y calefaccion central.",
    address: "Italia 2766, X5009 Córdoba",
    neighborhood: "Villa Cabrera",
    city: "Cordoba",
    rooms: 9,
    bedrooms: 4,
    bathrooms: 3,
    garages: 2,
    totalArea: 90,
    usableArea: 60,
    pool: true,
    grill: true,
    gasSupply: "red",
    images: [
        {url: photo1},
        {url: photo2},
        {url: photo3},
        {url: photo4},
        {url: photo5},
        {url: photo6},
        {url: photo7},
        {url: photo8},
        {url: photo9},
        {url: photo10},
        {url: photo11},
        {url: photo12},
        {url: photo13},
        {url: photo14},
        {url: photo15},
    ],
    video:"",
    },
    {id:"3",
    code:"DA0001",
    active: true,
    transaction: "alquiler",
    type: "departamento",
    title: "Departamento de 2 dormitorios",
    price: 500000,
    dollar: false,
    creditAb: false,
    description: "Departamento con dos dormitorios grandes, baño; patio con asador, pileta y chochera.",
    address: "Sergio Camargo 7966, X5021 Córdoba",
    neighborhood: "Arguello",
    city: "Cordoba",
    rooms: 6,
    bedrooms: 2,
    bathrooms: 1,
    garages: 1,
    totalArea: 50,
    usableArea: 30,
    pool: true,
    grill: true,
    gasSupply: "red",
    images: [
        {url: photo1},
        {url: photo2},
        {url: photo3},
        {url: photo4},
        {url: photo5},
        {url: photo6},
        {url: photo7},
        {url: photo8},
        {url: photo9},
        {url: photo10},
        {url: photo11},
        {url: photo12},
        {url: photo13},
        {url: photo14},
        {url: photo15},
    ],
    video:"",
    },
    {id:"4",
    code:"TV0001",
    active: true,
    transaction: "venta",
    type: "terreno",
    title: "Terreno en Arguello",
    price: 25000,
    dollar: true,
    creditAb: true,
    description: "Terreno de 80 metros cuadrados en arguello",
    address: "Sergio Camargo 7510, X5021 Córdoba",
    neighborhood: "Arguello",
    city: "Cordoba",
    rooms: 0,
    bedrooms: 0,
    bathrooms: 0,
    garages: 0,
    totalArea: 80,
    usableArea: 0,
    pool: false,
    grill: false,
    gasSupply: "no",
    images: [
        {url: photo1},
        {url: photo2},
        {url: photo3},
        {url: photo4},
        {url: photo5},
        {url: photo15},
    ],
    video:"",
    },  
]